version: '3'
services:
  calcite-avatica-go:
    build: .
    environment:
      PHOENIX_HOST: http://phoenix:8765
      HSQLDB_HOST: http://hsqldb:8765
    command: sh -c "export AVATICA_FLAVOR=HSQLDB && go test -v ./...; export AVATICA_FLAVOR=PHOENIX && go test -v ./..."
  phoenix:
    image: boostport/hbase-phoenix-all-in-one:1.3-4.13
  hsqldb:
    image: f21global/calcite-avatica:1.11.0-hypersql
    command: -u jdbc:hsqldb:mem:public