on:
  push:
    branches:
      - main
  pull_request:
name: Tests
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go_version: [1.18, 1.19]
        database:
          - [phoenix, 1.3-4.13]
          - [phoenix, 1.4-4.14]
          - [phoenix, 2.0-5.0]
          - [hsqldb, 1.18.0]
          - [hsqldb, 1.19.0]
          - [hsqldb, 1.20.0]
          - [hsqldb, 1.21.0]
          - [hsqldb, 1.22.0]

    runs-on: ubuntu-latest

    steps:
      - name: Check out Avatica-Go repository
        uses: actions/checkout@v3

      - name: Run tests
        env:
          PHOENIX_VERSION: ${{ matrix.database[1] }}
          HSQLDB_VERSION: ${{ matrix.database[1] }}
        run: docker compose run test-${{ matrix.database[0] }}